export const NotificationType = {
  EVENT_REMINDER_PARTICIPANT: 'EVENT_REMINDER_PARTICIPANT',
  EVENT_REMINDER_ORGANISER: 'EVENT_REMINDER_ORGANISER',
  EVENT_BROADCAST: 'EVENT_BROADCAST',
  EVENT_CHANGED_TIME: 'EVENT_CHANGED_TIME',
  EVENT_CHANGED_LOCATION: 'EVENT_CHANGED_LOCATION',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_INVITATION: 'EVENT_INVITATION',
} as const;

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];
